### ISSUE TITLE
Error with DiagnosticableMixin

### ISSUE THREAD

**Issue by prihodulkin** [ykrank/flutter_cupertino_datetime_picker#1]
Hi! Your package doesn't work because of using DiagnosticableMixin
 Error: Type 'DiagnosticableMixin' not found.
class DateTimePickerTheme with DiagnosticableMixin {

**Comment by ykrank** [comment]
> Hi! Your package doesn't work because of using DiagnosticableMixin
> Error: Type 'DiagnosticableMixin' not found.
> class DateTimePickerTheme with DiagnosticableMixin {

Your flutter is too old, after 1.20, flutter refactoring Diagnosticable with DiagnosticableMixin. so, you can update your flutter sdk, or replace DiagnosticableMixin with Diagnosticable.

**Comment by jiouloucse** [comment]
我的1.24.0 也在报这个问题

pub.flutter-io.cn/flutter_cupertino_date_picker-1.0.26+2/lib/src/date_picker_theme.dart:23:32: Error: Type 'DiagnosticableMixin' not found.
class DateTimePickerTheme with DiagnosticableMixin {

**Comment by ykrank** [comment]
我看了下，DiagnosticableMixin已经被Diagnostic替换了，之后将会更新适配stable版本的flutter
