### ISSUE TITLE
Month picker bug

### ISSUE THREAD

**Issue by DusBekas** [ykrank/flutter_cupertino_datetime_picker#10]
When I use the date yyyy-MMMM as a date format, the month picker seems to adding/decreasing the returned datetime value on onConfirm per 30 days, not per 1 month. So, it may cause issue for a month that has 31 days.

For an example, when I set the initialdate to now, 31st August. Then I move the month picker to June, it gives me 2021-07-01. But the correct returned date should be 2021-06-31 or to be precise 2021-06-30 right?

For now I'm mitigating this issue like this:
```
  DateTime _maxDateTime =
      DateTime(DateTime.now().year, DateTime.now().month, 1);
  DateTime _initialDateTime =
      DateTime(DateTime.now().year, DateTime.now().month, 1);
```

I hope anyone can check up on this issue.

**Comment by ykrank** [comment]
I change initdate to 2021-08-31 and move month to june, it gives 2021-06-01。so i think perhaps you can trans DateTime.now() to date of now.
