### ISSUE TITLE
分钟数据展示有问题

### ISSUE THREAD

**Issue by xyhxx** [ykrank/flutter_cupertino_datetime_picker#4]
![image](https://user-images.githubusercontent.com/51938216/114351485-441f3a00-9b9d-11eb-8953-74028c89d9fc.png)

我现在的时间是14：36 但是我选择的分钟范围只能是0~23

**Comment by xyhxx** [comment]
![image](https://user-images.githubusercontent.com/51938216/114359844-f90a2480-9ba6-11eb-858f-c9a419478a0a.png)
应该是这里的问题 分钟间隔只按照了索引的数据来算 没有考虑到开始和结束时间了

**Comment by ykrank** [comment]
Fix in version 2.0.1
