### ISSUE TITLE
Color of the selection boxes + their size

### ISSUE THREAD

**Issue by plavunov** [ykrank/flutter_cupertino_datetime_picker#6]
Hello,

Is it possible to update the theme settings to include the color of the selection boxes? It is currently gray only and I haven't found a way to change it.

Also, I have noticed that the selection boxes have a constant size. It would be great if that size could be adjusted as well (see in the image, "September" is seen outside of the selection box. Or maybe IntrinsicWidth could help here. 

Thanks!

<img width="337" alt="Screenshot 2021-06-03 at 20 24 58" src="https://user-images.githubusercontent.com/20342704/120686779-073f3780-c4aa-11eb-9d51-6253678cdf77.png">

**Comment by callmejm** [comment]
same problem here

**Comment by shoaibayaz** [comment]
I am creating a PR for this hopefully i will get merge
